version: "3.8"

services:
  db-server:
    image: postgres:14
    container_name: db-server
    environment:
      - POSTGRES_DB=dbname-ap-roove
      - POSTGRES_USER=dbuser-ap-roove
      - POSTGRES_PASSWORD=dbpasswd-ap-roove
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/:/var/lib/postgresql/data/
