spring:
  datasource:
    url: jdbc:postgresql://db-server:5432/dbname-ap-roove
    username: dbuser-ap-roove
    password: dbpasswd-ap-roove
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  error:
    include-message: always